In [1]:
import pandas as pd
from sklearn.cluster import KMeans

d:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
d:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [3]:
datafile = "../data/data.xls"
processedfile = "../tmp/data_processed.xls"

In [25]:
typelabel = {u'肝气郁结证型系数': 'A',
            u'热毒蕴结证型系数':'B',
            u'冲任失调证型系数':'C',
            u'气血两虚证型系数':'D',
            u'脾胃虚弱证型系数':'E',
            u'肝肾阴虚证型系数':'F'}

In [26]:
k = 4

In [27]:
data = pd.read_excel(datafile)

In [28]:
data

,肝气郁结证型系数,热毒蕴结证型系数,冲任失调证型系数,气血两虚证型系数,脾胃虚弱证型系数,肝肾阴虚证型系数,病程阶段,TNM分期,转移部位,确诊后几年发现转移
0,0.056,0.460,0.281,0.352,0.119,0.350,S4,H4,R1,J1
1,0.488,0.099,0.283,0.333,0.116,0.293,S4,H4,R1,J1
2,0.107,0.008,0.204,0.150,0.032,0.159,S4,H4,R2,J2
3,0.322,0.208,0.305,0.130,0.184,0.317,S4,H4,R2,J1
4,0.242,0.280,0.131,0.210,0.191,0.351,S4,H4,R2R5,J1
...,...,...,...,...,...,...,...,...,...,...
925,0.284,0.018,0.250,0.103,0.072,0.121,S1,H1,R0,J0
926,0.103,0.216,0.185,0.166,0.204,0.196,S1,H1,R0,J0
927,0.287,0.163,0.225,0.114,0.103,0.292,S1,H1,R0,J0
928,0.296,0.263,0.175,0.215,0.103,0.187,S1,H1,R0,J0
929,0.169,0.214,0.125,0.153,0.142,0.217,S1,H1,R0,J0

In [29]:
keys = list(typelabel.keys())

In [30]:
keys

['肝气郁结证型系数', '热毒蕴结证型系数', '冲任失调证型系数', '气血两虚证型系数', '脾胃虚弱证型系数', '肝肾阴虚证型系数']

In [31]:
result = pd.DataFrame()

In [32]:
for i in range(len(keys)):
    print('正在进行{}的聚类'.format(keys[i]))
    kmodel = KMeans(n_clusters=4, n_jobs=4)
    kmodel.fit(data[[keys[i]]].values)
    
    r1 = pd.DataFrame(kmodel.cluster_centers_, columns=[typelabel[keys[i]]])
    r2 = pd.Series(kmodel.labels_).value_counts()
    r2 = pd.DataFrame(r2, columns=[typelabel[keys[i]]+'n'])
    r = pd.concat([r1, r2], axis=1).sort_values(typelabel[keys[i]])
    r.index=[1, 2, 3, 4]
    c = r[typelabel[keys[i]]]
    r[typelabel[keys[i]]] = c.rolling(window=2).mean()
    r[typelabel[keys[i]]][1] = 0.0
    result = result.append(r.T)

正在进行肝气郁结证型系数的聚类
正在进行热毒蕴结证型系数的聚类
正在进行冲任失调证型系数的聚类
正在进行气血两虚证型系数的聚类
正在进行脾胃虚弱证型系数的聚类
正在进行肝肾阴虚证型系数的聚类

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [33]:
result

        1           2           3           4
A     0.0    0.180011    0.258551    0.352043
An  248.0  351.000000  278.000000   53.000000
B     0.0    0.147818    0.284702    0.450267
Bn  316.0  391.000000  169.000000   54.000000
C     0.0    0.201910    0.288684    0.423325
Cn  296.0  393.000000  206.000000   35.000000
D     0.0    0.174400    0.253486    0.360007
Dn  298.0  367.000000  221.000000   44.000000
E     0.0    0.152698    0.257873    0.376062
En  273.0  319.000000  245.000000   93.000000
F     0.0    0.179143    0.261386    0.354643
Fn  200.0  237.000000  265.000000  228.000000